apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: odoo-system
  labels:
    app: odoo
spec:
  selector:
    app: odoo
  ports:
  - name: web
    port: 80
    targetPort: 8069
    nodePort: 30069
  - name: longpolling
    port: 8072
    targetPort: 8072
    nodePort: 30072
  type: NodePort
