apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: odoo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres-headless"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 999  # PostgreSQL 17 vẫn sử dụng group 999
      initContainers:
      - name: init-postgres-dirs
        image: busybox:latest
        command:
        - sh
        - -c
        - |
          mkdir -p /var/lib/postgresql/data/pgdata/pg_log
          chmod 700 /var/lib/postgresql/data/pgdata
          chown -R 999:999 /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        securityContext:
          runAsUser: 0
      containers:
      - name: postgres
        image: postgres:17  # Sử dụng đúng phiên bản PostgreSQL 17
        securityContext:     # Thêm cấu hình này để chạy PostgreSQL với user postgres
          runAsUser: 999     # User ID postgres
          runAsGroup: 999    # Group ID postgres
        command:
        - "bash"
        - "-c"
        - |
          cp /postgresql-config/postgresql.conf /tmp/postgresql.conf
          exec postgres -c config_file=/tmp/postgresql.conf
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-secrets
              key: db-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - odoo
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - odoo
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - pg_isready
            - -U
            - odoo
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgresql-config
          mountPath: /postgresql-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
      volumes:
      - name: postgresql-config
        configMap:
          name: postgres-config
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc