apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd
  namespace: odoo-system
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.1.11:6789,192.168.1.12:6789,192.168.1.13:6789
  adminId: admin
  adminSecretName: ceph-admin-secret
  adminSecretNamespace: odoo-system
  pool: kubernetes
  userId: admin
  userSecretName: ceph-admin-secret
  fsType: ext4
reclaimPolicy: Retain
