apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-image-storage-pvc
  namespace: odoo-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
  volumeName: local-image-storage-pv
