apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo-system
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    data_dir = /var/lib/odoo
    admin_passwd = admin123
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = admin
    db_name = odoo
    db_template = template0
    proxy_mode = True
    limit_request = 8192
    limit_memory_soft = 2147483648
    limit_memory_hard = 2684354560
    #workers = 4 khi có worker sẽ lỗi socket chuyển sang dùng max_cron...
    max_cron_threads = 2
    # Tăng số luồng cron để cải thiện hiệu suất background
    without_demo = True
    list_db = True
    # Redis configuration
    session_store = redis
    session_redis = redis:6379:0
    cache_store = redis
    cache_redis = redis:6379:1
    # WebSocket improvements
    proxy_buffering = off
    proxy_connect_timeout = 3600
    proxy_read_timeout = 3600
    proxy_send_timeout = 3600
    longpolling_port = 8072
    #longpolling_port = False
    gevent_port = 8072
