apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
  namespace: odoo-system
data:
  odoo.conf: |
    [options]
    addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    data_dir = /var/lib/odoo
    # admin_passwd = admin123
    db_host = postgres
    db_port = 5432
    db_user = odoo
    db_password = admin
    # db_name = odoo
    db_template = template0
    
    # Proxy config quan trọng cho Cloudflared
    proxy_mode = True
    proxy_buffering = off
    proxy_connect_timeout = 3600
    proxy_read_timeout = 3600
    proxy_send_timeout = 3600
    
    # Đặt URL cố định cho hệ thống
    web_base_url = https://weldcom.mayhanthongminh.com
    
    # Thiết lập các header security
    trust_x_forwarded = True
    secure_hsts_header = True
    cors_origin = https://weldcom.mayhanthongminh.com
    
    # WebSocket config
    gevent_port = 8072
    longpolling_port = 8072
    websocket_keep_alive_timeout = 600
    websocket_rate_limit_burst = 30
    websocket_rate_limit_delay = 10
    
    # Redis configuration
    session_store = redis
    session_redis = redis:6379:0
    cache_store = redis
    cache_redis = redis:6379:1
    
    # Các cài đặt khác
    without_demo = True
    list_db = True
    limit_request = 8192
    limit_memory_soft = 6039797760
    limit_memory_hard = 7247757312
    max_cron_threads = 4